version: '3.1'

services:
  db:
    image: postgres:12.2
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432